const songs=[

    "01 - Era7capone ft. Batuflex - CISTAK prod by. Narco",
    "02 - Ati242 - Değişmene Rağmen",
    "03 - Semicenk & Doğu Swag - Küle Dönmüşsün",
    "04 - Ege - BLOK3 - ESC_BAR",
    "05 - Simge - Önümüz Yaz",
    "06 - Lais Records - Era7capone ft. NASTEISHA - İNTİHAR",
    "07 - Dedublüman - Sen Bilmezsin",
    "08 - Luca VI11 - Gaflet",
    "09 - Mert Demir - Ölüyorum Anla",
    "10 - Gülşen - BAL",
    "11 - Lvbel C5 - Sezen Aksu",
    "12 - Lais Records - Gülşen & Murat Boz & Lvbel C5 & Akdo - İLTİMAS X SUBMARINER",
    "13 - Emre Fel - Sana El Pençe Durmam",
    "14 - Mela Bedel - Ben Sana Gelemem",
    "15 - Bengü - Saat 03.00 (By Volga Tamöz)",
    "16 - KÖFN - X Simge - Yakışıklı",
    "17 - Reynmen - Renklensin",
    "18 - Lvbel C5 - nE !",
    "19 - Semicenk & Rast - Canın Sağ Olsun",
    "20 - Duman - Kufi",
    "21 - Zeynep Bastık - Lan",
    "22 - Cevher - Merhametsiz",
    "23 - Rapkology - BLOK3 x Stefflon Don - Habibi",
    "24 - AKDO & cakal - DOYAMADIM",
    "25 - Burak Bulut & Ebru Yaşar - Kehribar",
    "26 - Lvbel C5 & Melis Kar - DACIA X YATIYA (Remix)",
    "27 - Semicenk - Geri Dönemedim",
    "28 - Yener Çevik - Hüznü Hecem",
    "29 - Mabel Matiz - Kömür",
    "30 - Aydın Kurtoğlu - Hayırlı Günler (Akustik Versiyon)",
    "31 - Semicenk - Batık Gemi",
    "32 - Blok3 - aklına ben gelicem",
    "33 - İzel - Düşer O",
    "34 - Semicenk - Tek Başıma",
    "35 - Çiğdem - Teke Tek",
    "36 - Bengü Beker - Sana Yıldızları Ödediğimden",
    "37 - cakal - Damlarsın",
    "38 - Amo988 - Yüreğim Ağlar",
    "39 - Gülden Karaböcek - Sen Evlisin",
    "40 - M Lisa - ARABA",
    "41 - Hande Yener - Sopa ( Clup Remıx )",
    "42 - Emir Can İğrek - Bir Karanfil (Yapay Zeka)",
    "43 - Motive - pVg",
    "44 - Bayhan - Tiryakinim",
    "45 - Blok3 - LAF",
    "46 - Onur Can Özcan & Emir Can İğrek - Bir Karanfil",
    "47 - Aleyna Tilki - Başıma Belasın",
    "48 - Çağan Şengül - Çok Yazık",
    "49 - Kubilay Karça - Celladına Aşık",
    "50 - Sufle - Lakin",
  ]
  export default songs